<?php

/**
 * @file pi.module
 * This file contains all of the hook implementations for Percolate Integration.
 */

include_once('phpercolate/Api.php');

/**
 * Implements hook_menu().
 */
function pi_menu() {
  $items['admin/config/content/percolate'] = array(
    'title' => t('Percolate Integration'),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pi_settings_form'),
    'access arguments' => array('configure pi'),
  );
  
  return $items;
}


/**
 * Implements hook_permission().
 */
function pi_permission() {
  return array(
    'configure pi' => array(
      'title' => t('Configure Percolate integration'),
    ),
  );
}


/**
 * Page callback for admin/config/content/percolate. Provides a settings form.
 */
function pi_settings_form($form, &$form_state) {
  $form = array();
  $key = variable_get('pi_api_key', '');
  
  $form['pi_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#default_value' => variable_get('pi_api_key', ''),
  );
  
  
  $api = new Percolate_Api($key);
  try {
    dpm($api->getUserPosts('13891', 20));
  }
  catch (Percolate_Exception $e) {
    dpm((string)$e);
  }
  
  return system_settings_form($form);
}